[package]
name = "mdswp"
version = "0.1.0"
authors = ["dousamichal0807 <dousamichal0807 at seznam dot cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"